name: nitro
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  shelf: ^1.4.2
  env_guard: ^1.3.1
  shelf_router: ^1.1.4
  vine: ^1.7.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  shelf_multipart: ^2.0.1
